// <auto-generated />
using System;
using JPPhotoManager.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JPPhotoManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240825005737_AddConvertAssetsDirectoriesDefinition")]
    partial class AddConvertAssetsDirectoriesDefinition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("JPPhotoManager.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FileCreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileModificationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageRotation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ThumbnailCreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThumbnailPixelHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThumbnailPixelWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId");

                    b.HasIndex("FolderId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("JPPhotoManager.Domain.Entities.ConvertAssetsDirectoriesDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteAssetsNotInSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeSubFolders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConvertAssetsDirectoriesDefinitions");
                });

            modelBuilder.Entity("JPPhotoManager.Domain.Entities.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("JPPhotoManager.Domain.Entities.RecentTargetPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecentTargetPaths");
                });

            modelBuilder.Entity("JPPhotoManager.Domain.Entities.SyncAssetsDirectoriesDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteAssetsNotInSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeSubFolders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncAssetsDirectoriesDefinitions");
                });

            modelBuilder.Entity("JPPhotoManager.Domain.Entities.Asset", b =>
                {
                    b.HasOne("JPPhotoManager.Domain.Entities.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });
#pragma warning restore 612, 618
        }
    }
}
